import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TrackVisit from "@/components/TrackVisit.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          style={{
            backgroundImage: "url('/background.svg')",
            backgroundSize: "cover",
            minHeight: "100vh",
          }}
        >
          <TrackVisit />
          {children}
        </div>
      </body>
    </html>
  );
}
